name: Release

on:
    workflow_dispatch:
    push:
        branches: [ master ]
jobs:
    getRelease:
        name: getRelease
        runs-on: cx-public-ubuntu-x64
        outputs:
            git_tag: ${{ steps.semantic_release_info.outputs.git_tag }}
            version: ${{ steps.semantic_release_info.outputs.version }}
            notes: ${{ steps.semantic_release_info.outputs.notes }}
    buildAndRelease:
        name: buildAndRelease
        runs-on: cx-public-ubuntu-x64
        steps:
            -   name: Gets release info
                id: semantic_release_info
                if: github.event_name == 'workflow_dispatch'
                uses: jossef/action-semantic-release-info@79e9bfdddf4c53d5e710728013d76a128e1f9b0b # v2.1.0
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            -   name: Checkout
                uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
            -   name: Set up JDK 1.8
                uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1.4.4
                with:
                    java-version: 1.8
            -   name: Build with Maven
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: ./mvnw clean verify --show-version --batch-mode --errors -PbuildKar -Drevision=${{ needs.test.outputs.version }}

            -   name: Release
                uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
                with:
                    files: |
                        ./target/*.kar
                    tag_name: ${{ needs.getRelease.outputs.git_tag }}
                    body: ${{ needs.getRelease.outputs.notes }}
                    draft: false
                    prerelease: false
            -   name: Push
                uses: ad-m/github-push-action@d30dc2d070765d7e509df00c34c5fa2dd636ff74 # master
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    branch: master
