name: Release

on:
    workflow_dispatch:
    push:
        branches: [ master ]
jobs:
    getRelease:
        name: getRelease
        runs-on: ubuntu-latest
        outputs:
            git_tag: ${{ steps.semantic_release_info.outputs.git_tag }}
            version: ${{ steps.semantic_release_info.outputs.version }}
            notes: ${{ steps.semantic_release_info.outputs.notes }}
    buildAndRelease:
        name: buildAndRelease
        runs-on: ubuntu-latest
        steps:
            -   name: Gets release info
                id: semantic_release_info
                if: github.event_name == 'workflow_dispatch'
                uses: jossef/action-semantic-release-info@v2.1.0
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
            -   name: Build with Maven
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: ./mvnw clean verify --show-version --batch-mode --errors -PbuildKar -Drevision=${{ needs.test.outputs.version }}

            -   name: Release
                uses: softprops/action-gh-release@v0.1.15
                with:
                    files: |
                        ./target/*.kar
                    tag_name: ${{ needs.getRelease.outputs.git_tag }}
                    body: ${{ needs.getRelease.outputs.notes }}
                    draft: false
                    prerelease: false
            -   name: Push
                uses: ad-m/github-push-action@master
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    branch: master
